# doctai Configuration
# This is the default config for the doctai project itself

docs:
  - README.md
  - examples/sample-documentation.md

provider: anthropic
model: claude-sonnet-4-20250514

stop_on_failure: false

max_iterations: 3

timeout: 120

